// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
)

type Account struct {
	ID        int32        `json:"id"`
	Owner     string       `json:"owner"`
	Balance   string       `json:"balance"`
	Currency  string       `json:"currency"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Entry struct {
	ID        int32         `json:"id"`
	AccountID sql.NullInt32 `json:"account_id"`
	Amount    string        `json:"amount"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Transfer struct {
	ID            int32         `json:"id"`
	FromAccountID sql.NullInt32 `json:"from_account_id"`
	ToAccountID   sql.NullInt32 `json:"to_account_id"`
	Amount        string        `json:"amount"`
	CreatedAt     sql.NullTime  `json:"created_at"`
}
